In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cross_validation import train_test_split
Data =[]
Data.append({'text':'In the living room of a house in Banjarmasin South Kalimantan Zakaria was busy choosing a book from the shelf','sentiment':'0'})
Data.append({'text':'The eleven year old sat in his wheelchair his right knee swollen and wrapped in bandages','sentiment':'0'})
Data.append({'text':'Zakaria who hails from Barabai in Hulu Sungai Tengah Regency South Kalimantan suffers from bone cancer','sentiment':'1'})
Data.append({'text':'His mother Masrah took him to the provincial capital Banjarmasin to receive medical treatment at the citys Ulin Regional Hospital','sentiment':'1'})
Data.append({'text':'For the past two weeks both had been staying at the Rumahku My Home shelter for children with cancer','sentiment':'1'})
Data.append({'text':'We have to go back and forth to the hospital so Im grateful we have a place to stay here Masrah said','sentiment':'1'})
Data.append({'text':'At the shelter five other young patients were staying with their parents','sentiment':'1'})
Data.append({'text':'All of them were from lower middleclass families including Herma Adam and her father Heri Suwarso','sentiment':'-1'})
Data.append({'text':'Herma suffers from leukemia and has undergone chemotherapy since January two thousand and sixteen','sentiment':'-1'})
Data.append({'text':'I took her to Ulin Hospital on reference from the state hospital at Batulicin in Tanah Bumbu Regency said Heri thirty five','sentiment':'0'})
Data.append({'text':'Hermas doctors said she had to receive regular chemotherapy for two years','sentiment':'-1'})
Data.append({'text':'After six months of medical treatment Heri said that his daughters cancer cells had shrunk to only one point five percent','sentiment':'1'})
Data.append({'text':'But the doctor advised us to stay in Banjarmasin for a while until she is much better Heri said','sentiment':'0'})
Data.append({'text':'Heri was hopeful that her daughter would make progress','sentiment':'1'})
Data.append({'text':'At first the man who worked as a truck driver was worried that they would not be able to stay long in Banjarmasin for Hermas treatment because of the high costs','sentiment':'-1'})
Data.append({'text':'But a nurse they came across in the Ulin Hospital lobby suggested they stay at the Rumahku shelter','sentiment':'1'})
Data.append({'text':'It provides free accommodation for cancer patients from outside Banjarmasin','sentiment':'1'})
Data.append({'text':'Heri took the nurses advice and moved in January','sentiment':'1'})
Data.append({'text':'Not only did they get a place to stay the shelter also provided free pickup service from and to the hospital food and some medicine','sentiment':'1'})
Data.append({'text':'Im thankful that we can stay here Heri said','sentiment':'0'})
Data.append({'text':'He added that Hermas treatment was paid for by the national health insurance program','sentiment':'1'})


C:\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
new_data = pd.DataFrame.from_dict(Data)
new_data

sentiment                                               text
0          0  In the living room of a house in Banjarmasin S...
1          0  The eleven year old sat in his wheelchair his ...
2          1  Zakaria who hails from Barabai in Hulu Sungai ...
3          1  His mother Masrah took him to the provincial c...
4          1  For the past two weeks both had been staying a...
5          1  We have to go back and forth to the hospital s...
6          1  At the shelter five other young patients were ...
7         -1  All of them were from lower middleclass famili...
8         -1  Herma suffers from leukemia and has undergone ...
9          0  I took her to Ulin Hospital on reference from ...
10        -1  Hermas doctors said she had to receive regular...
11         1  After six months of medical treatment Heri sai...
12         0  But the doctor advised us to stay in Banjarmas...
13         1  Heri was hopeful that her daughter would make ...
14        -1  At first the man who worked as a truck driver ...
15         1  But a nurse they came across in the Ulin Hospi...
16         1  It provides free accommodation for cancer pati...
17         1   Heri took the nurses advice and moved in January
18         1  Not only did they get a place to stay the shel...
19         0        Im thankful that we can stay here Heri said
20         1  He added that Hermas treatment was paid for by...

In [3]:
X = new_data.text
y = new_data.sentiment
print(X.shape)
print(y.shape)

(21,)
(21,)


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(18,)
(3,)
(18,)
(3,)


In [5]:
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)


In [6]:
X_test_dtm = vect.transform(X_test)
X_test_dtm


<3x174 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

## SGDC CLassifer

In [84]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
%time clf.fit(X_train_dtm, y_train)
y_pred_class = clf.predict(X_test_dtm)

Wall time: 0 ns


In [85]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.6666666666666666

In [86]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[0, 1],
       [0, 2]], dtype=int64)

In [87]:
test1 = ['regular for']
new_article_vect = vect.transform(test1)
clf.predict(new_article_vect)

array(['-1'], dtype='<U2')

## Decision Tree

In [89]:
from sklearn import tree
from sklearn.metrics import accuracy_score
clf = tree.DecisionTreeClassifier()
%time clf.fit(X_train_dtm, y_train)
y_pred_class = clf.predict(X_test_dtm)

Wall time: 0 ns


In [90]:
print("Predicting...")
prediction = clf.predict(X_test_dtm)

Predicting...


In [91]:
print("Prediction:",prediction)
accuracy = accuracy_score(y_test, prediction)

Prediction: ['1' '1' '1']


In [93]:
metrics.accuracy_score(y_test, y_pred_class)
print('Accuracy:', accuracy)

Accuracy: 0.6666666666666666


In [92]:
new_article = ['The eleven year old sat in his wheelchair his right']
new_article_vect = vect.transform(new_article)
clf.predict(new_article_vect)


array(['1'], dtype=object)

## Clustering (Data)

In [8]:

cluster_data = pd.DataFrame(Data,columns=['text'])
cluster_data


text
0   In the living room of a house in Banjarmasin S...
1   The eleven year old sat in his wheelchair his ...
2   Zakaria who hails from Barabai in Hulu Sungai ...
3   His mother Masrah took him to the provincial c...
4   For the past two weeks both had been staying a...
5   We have to go back and forth to the hospital s...
6   At the shelter five other young patients were ...
7   All of them were from lower middleclass famili...
8   Herma suffers from leukemia and has undergone ...
9   I took her to Ulin Hospital on reference from ...
10  Hermas doctors said she had to receive regular...
11  After six months of medical treatment Heri sai...
12  But the doctor advised us to stay in Banjarmas...
13  Heri was hopeful that her daughter would make ...
14  At first the man who worked as a truck driver ...
15  But a nurse they came across in the Ulin Hospi...
16  It provides free accommodation for cancer pati...
17   Heri took the nurses advice and moved in January
18  Not only did they get a place to stay the shel...
19        Im thankful that we can stay here Heri said
20  He added that Hermas treatment was paid for by...

In [9]:
X = cluster_data.text
print(X.shape)

(21,)


In [10]:
vect.fit(X)
tes = vect.transform(X)
tes

<21x190 sparse matrix of type '<class 'numpy.int64'>'
	with 325 stored elements in Compressed Sparse Row format>

In [15]:
from scipy.spatial import distance

def compute_s(i, x, labels, clusters):
	norm_c= len(clusters)
	s = 0
	for x in clusters:
		# print x
		s += distance.euclidean(x, clusters[i])
	return s

def compute_Rij(i, j, x, labels, clusters, nc):
	Rij = 0
	try:
		# print "h"
		d = distance.euclidean(clusters[i],clusters[j])
		# print d
		Rij = (compute_s(i, x, labels, clusters) + compute_s(j, x, labels, clusters))/d
		# print Rij
	except:
		Rij = 0	
	return Rij

def compute_R(i, x, labels, clusters, nc): 
	list_r = []
	for i in range(nc):
		for j in range(nc):
			if(i!=j):
				temp = compute_Rij(i, j, x, labels, clusters, nc)
				list_r.append(temp)

	return max(list_r)

def compute_DB_index(x, labels, clusters, nc):
	# print x
	sigma_R = 0.0
	for i in range(nc):
		sigma_R = sigma_R + compute_R(i, x, labels, clusters, nc)

	DB_index = float(sigma_R)/float(nc) 
	return DB_index

## K-Means

In [39]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2, random_state=0).fit(tes)
cek = kmeans.labels_
cek

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1])

In [106]:
dfd=pd.DataFrame(cek, columns=['Hasil Cluster']) 
result = pd.concat([cluster_data,dfd], axis=1, sort=False)
result

text  Hasil Cluster
0   In the living room of a house in Banjarmasin S...              0
1   The eleven year old sat in his wheelchair his ...              0
2   Zakaria who hails from Barabai in Hulu Sungai ...              0
3   His mother Masrah took him to the provincial c...              0
4   For the past two weeks both had been staying a...              0
5   We have to go back and forth to the hospital s...              1
6   At the shelter five other young patients were ...              0
7   All of them were from lower middleclass famili...              0
8   Herma suffers from leukemia and has undergone ...              0
9   I took her to Ulin Hospital on reference from ...              0
10  Hermas doctors said she had to receive regular...              0
11  After six months of medical treatment Heri sai...              0
12  But the doctor advised us to stay in Banjarmas...              0
13  Heri was hopeful that her daughter would make ...              0
14  At first the man who worked as a truck driver ...              2
15  But a nurse they came across in the Ulin Hospi...              0
16  It provides free accommodation for cancer pati...              0
17   Heri took the nurses advice and moved in January              0
18  Not only did they get a place to stay the shel...              1
19        Im thankful that we can stay here Heri said              0
20  He added that Hermas treatment was paid for by...              0

In [70]:
centroids = kmeans.cluster_centers_
labels = kmeans.labels_
index_db_val = compute_DB_index(tes, labels, centroids, n)
print ("The value of Davies Bouldin index for a K-Means cluser of size " + str(n) + " is: " + str(index_db_val))

The value of Davies Bouldin index for a K-Means cluser of size 2 is: 2.0


## Spectral Clustering

In [46]:
from sklearn.cluster import SpectralClustering
clustering = SpectralClustering(n_clusters=3,assign_labels="discretize",random_state=0).fit(tes)
cek1 = clustering.labels_
cek1

array([0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 2, 1, 0, 1, 0, 0, 2, 1],
      dtype=int32)

In [107]:
dfd1=pd.DataFrame(cek1, columns=['Hasil Cluster']) 
result = pd.concat([cluster_data,dfd1], axis=1, sort=False)
result

text  Hasil Cluster
0   In the living room of a house in Banjarmasin S...              0
1   The eleven year old sat in his wheelchair his ...              0
2   Zakaria who hails from Barabai in Hulu Sungai ...              1
3   His mother Masrah took him to the provincial c...              0
4   For the past two weeks both had been staying a...              0
5   We have to go back and forth to the hospital s...              2
6   At the shelter five other young patients were ...              0
7   All of them were from lower middleclass famili...              0
8   Herma suffers from leukemia and has undergone ...              0
9   I took her to Ulin Hospital on reference from ...              0
10  Hermas doctors said she had to receive regular...              1
11  After six months of medical treatment Heri sai...              1
12  But the doctor advised us to stay in Banjarmas...              1
13  Heri was hopeful that her daughter would make ...              2
14  At first the man who worked as a truck driver ...              1
15  But a nurse they came across in the Ulin Hospi...              0
16  It provides free accommodation for cancer pati...              1
17   Heri took the nurses advice and moved in January              0
18  Not only did they get a place to stay the shel...              0
19        Im thankful that we can stay here Heri said              2
20  He added that Hermas treatment was paid for by...              1